services:
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - ./src/.env
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: always

  publisher:
    build:
      dockerfile: src/Dockerfile.pub
    env_file:
      - ./src/.env
    restart: always

  consumer:
    build:
      dockerfile: src/Dockerfile.cons
    env_file:
      - ./src/.env
    restart: always