FROM python:3.12-alpine

LABEL authors="seeu"

WORKDIR /opt/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/opt/app

COPY . .

RUN  pip install --upgrade pip \
     && pip install --no-cache-dir -r src/requirements.txt


ENTRYPOINT ["python", "src/publish/publisher.py"]